package javaapplication3;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication3.Ramka.List_connected_id;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author filemon
 */
public class Hotel_logs extends javax.swing.JFrame {

    /**
     * Niezbędne okno do debugowania, oglądania tego co dzieje się miedzy aplikacjami a serwerami
     */
    public Hotel_logs() 
    {
    initComponents();
    setDefaultCloseOperation(this.HIDE_ON_CLOSE);
    List_connected_id.setModel(Ramka.List_connected_id);
    List_unconnected_rooms.setModel(Ramka.List_unconnected_rooms);

    try {
        label_bg.setIcon(new ImageIcon(ImageIO.read(new File("main_bg.jpg"))));
        } 
    catch (IOException ex) 
         {
        Logger.getLogger(Ramka.class.getName()).log(Level.SEVERE, null, ex);
        }
    
  //  List_connected_id.setBackground(new Color(0,0,0,125));
  //  List_unconnected_rooms.setBackground(new Color(0,0,0,125));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        List_connected_id = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        List_unconnected_rooms = new javax.swing.JList<>();
        label_bg = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        List_unconnected_rooms1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roomie Server - Logs");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setColumns(20);
        panel.setRows(5);
        jScrollPane1.setViewportView(panel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 236, 762, 229));

        List_connected_id.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(List_connected_id);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 48, 100, 182));

        jLabel1.setText("Connected ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 19, -1, -1));

        jLabel2.setText("All Unconnected Rooms");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 19, -1, -1));

        List_unconnected_rooms.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(List_unconnected_rooms);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 48, 110, 182));
        getContentPane().add(label_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 480));

        List_unconnected_rooms1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(List_unconnected_rooms1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 48, 110, 182));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_logs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> List_connected_id;
    private javax.swing.JList<String> List_unconnected_rooms;
    private javax.swing.JList<String> List_unconnected_rooms1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_bg;
    public static javax.swing.JTextArea panel;
    // End of variables declaration//GEN-END:variables
}
