package javaapplication3;

import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author filemon
 */
public class Hotel_dodaj extends javax.swing.JFrame {

    /**
     * Nowa forma Hotel_dodaj
     * 
     * Dodaje pokój, do listy pokoi - Ogólnie tworzy konta na które można się zalogować.
     * 
     */
    public Hotel_dodaj() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
            try {
                  label_bg.setIcon(new ImageIcon(ImageIO.read(new File("main_bg.jpg"))));
                } 
            catch (IOException ex) 
                {
                  Logger.getLogger(Ramka.class.getName()).log(Level.SEVERE, null, ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        field_type_number = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        field_generate_password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        field_checkIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        field_checkOut = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        field_type_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        field_type_surname = new javax.swing.JTextField();
        button_add_room = new javax.swing.JButton();
        label_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roomie Server - Dodaj");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("DODAJ POKÓJ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 12, -1, -1));

        field_type_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_type_numberActionPerformed(evt);
            }
        });
        getContentPane().add(field_type_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 51, 128, -1));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Nr. Pokoju:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 56, -1, -1));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Hasło Pokoju:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 149, -1, -1));

        field_generate_password.setEditable(false);
        getContentPane().add(field_generate_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 144, 128, -1));

        jButton1.setBackground(new java.awt.Color(55, 129, 149));
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Generuj Haslo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 88, 213, 44));

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Okres Zameldowania");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 51, -1, -1));

        field_checkIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_checkInActionPerformed(evt);
            }
        });
        getContentPane().add(field_checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 80, 70, -1));

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Od:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 85, -1, -1));

        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("do:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 85, -1, -1));
        getContentPane().add(field_checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 80, 70, -1));

        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Opcjonalnie:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 217, -1, -1));

        jLabel8.setText("Imię:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 252, -1, -1));
        getContentPane().add(field_type_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 252, 157, -1));

        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Nazwisko:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 285, -1, -1));
        getContentPane().add(field_type_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 285, 157, -1));

        button_add_room.setBackground(new java.awt.Color(55, 129, 149));
        button_add_room.setForeground(new java.awt.Color(254, 254, 254));
        button_add_room.setText("Dodaj Pokój");
        button_add_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_add_roomActionPerformed(evt);
            }
        });
        getContentPane().add(button_add_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 257, 186, 55));

        label_bg.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(label_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 330));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_type_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_type_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_type_numberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    field_generate_password.setText(GenerujHaslo());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void field_checkInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_checkInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_checkInActionPerformed

    private void button_add_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add_roomActionPerformed
   if(field_type_number.getText().toString().equals("")) Ramka.logs.panel.append("Nie podano numeru pokoju\n");
   else if (!field_type_number.getText().matches("\\d+")) Ramka.logs.panel.append("Bledny numer pokoju\n");
   else if (Ramka.List_unconnected_rooms.contains(field_type_number.getText())||Ramka.List_connected_rooms.contains(field_type_number.getText()))  Ramka.logs.panel.append("Pokoj jest juz zarejestrowany\n");
   else if (field_generate_password.getText().toString().equals("")) Ramka.logs.panel.append("Nie wygenerowano hasla");
   else
   {
       Pokoje pokoj = new Pokoje(Integer.parseInt(field_type_number.getText().toString()),field_generate_password.getText().toString());
       Ramka.pokoje[Integer.parseInt(field_type_number.getText().toString())]=pokoj;
       Ramka.List_unconnected_rooms.addElement(field_type_number.getText());
   }
        
    }//GEN-LAST:event_button_add_roomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_dodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_dodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_dodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_dodaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_dodaj().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add_room;
    private javax.swing.JTextField field_checkIn;
    private javax.swing.JTextField field_checkOut;
    private javax.swing.JTextField field_generate_password;
    private javax.swing.JTextField field_type_name;
    private javax.swing.JTextField field_type_number;
    private javax.swing.JTextField field_type_surname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_bg;
    // End of variables declaration//GEN-END:variables


    
    
    
    
    
public String GenerujHaslo() 
    {
       SecureRandom random = new SecureRandom(); 
       return new BigInteger(15, random).toString(32);
    }




}


