package javaapplication3;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication3.Ramka.label_background_img;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author filemon
 */
public class Hotel_request_info extends javax.swing.JFrame {

    /**
     * Okno pojawiające się po naciśnięciu w button powiadomienia. 
     * 
     * Zawiera wszystkie ifnormacje o poleceniu od klienta
     */
    public Hotel_request_info() 
    {
        
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        
        try 
        {
        label_bg.setIcon(new ImageIcon(ImageIO.read(new File("first_bg.jpg"))));
        } 
        catch (IOException ex) 
        {
        Logger.getLogger(Ramka.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jScrollPane1.setBackground(new Color(0,0,0,0));
        area_request_info.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_request_info = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_request_info = new javax.swing.JTextArea();
        close_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Roomie Server");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_request_info.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        label_request_info.setForeground(new java.awt.Color(254, 254, 254));
        label_request_info.setText("INFORMACJE");
        getContentPane().add(label_request_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 12, -1, -1));

        area_request_info.setEditable(false);
        area_request_info.setColumns(20);
        area_request_info.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        area_request_info.setLineWrap(true);
        area_request_info.setRows(5);
        area_request_info.setText("Testowa tresc tego co wylal user i cos dla dlugosci\n");
        area_request_info.setToolTipText("");
        area_request_info.setWrapStyleWord(true);
        area_request_info.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(area_request_info);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 440, 175));

        close_button.setBackground(new java.awt.Color(55, 129, 149));
        close_button.setText("Wykonane");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 238, 149, 50));

        jButton2.setBackground(new java.awt.Color(55, 129, 149));
        jButton2.setText("Zamknij");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 155, 50));
        getContentPane().add(label_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_close_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_request_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_request_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_request_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_request_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_request_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea area_request_info;
    public static javax.swing.JButton close_button;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_bg;
    public static javax.swing.JLabel label_request_info;
    // End of variables declaration//GEN-END:variables
}
